### ISSUE TITLE
시크릿키 노출

### ISSUE THREAD

**Issue by loopback-kr** [cr3ux53c/hello-django#1]
https://github.com/cr3ux53c/hello-django/blob/55def3a8ad343082a0bdb70e29779f273a5a7dd2/hello_django/settings.py#L23
이렇게 올리면 안돼요!!

**Comment by cr3ux53c** [comment]
넹. 실습 예제라서 괜찮아요!~~
[깃허브 소개 영상 (한국어 자막)](https://www.youtube.com/watch?v=w3jLJU7DT5E)
![de3fe7661dfb69e32a8015e682659f634594089c](https://user-images.githubusercontent.com/28856527/55028153-61325000-504a-11e9-9ae2-9f5abcefb331.jpg)

**Comment by loopback-kr** [comment]
다행입니다.
